# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1270, 680)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(249, 249, 249);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(40, 60))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.homeTab = QtWidgets.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.gridLayout = QtWidgets.QGridLayout(self.homeTab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.defaultTempValueLabel = QtWidgets.QLabel(self.homeTab)
        self.defaultTempValueLabel.setText("")
        self.defaultTempValueLabel.setObjectName("defaultTempValueLabel")
        self.gridLayout_3.addWidget(self.defaultTempValueLabel, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        self.rangeLabel = QtWidgets.QLabel(self.homeTab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.rangeLabel.setFont(font)
        self.rangeLabel.setStyleSheet("qproperty-alignment:\'AlignCenter\'")
        self.rangeLabel.setObjectName("rangeLabel")
        self.gridLayout_3.addWidget(self.rangeLabel, 1, 0, 1, 1)
        self.rateLabel = QtWidgets.QLabel(self.homeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rateLabel.sizePolicy().hasHeightForWidth())
        self.rateLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.rateLabel.setFont(font)
        self.rateLabel.setStyleSheet("qproperty-alignment:\'AlignCenter\'")
        self.rateLabel.setObjectName("rateLabel")
        self.gridLayout_3.addWidget(self.rateLabel, 2, 0, 1, 1)
        self.rangeValueLabel = QtWidgets.QLabel(self.homeTab)
        self.rangeValueLabel.setText("")
        self.rangeValueLabel.setObjectName("rangeValueLabel")
        self.gridLayout_3.addWidget(self.rangeValueLabel, 1, 1, 1, 1)
        self.rateValueLabel = QtWidgets.QLabel(self.homeTab)
        self.rateValueLabel.setText("")
        self.rateValueLabel.setObjectName("rateValueLabel")
        self.gridLayout_3.addWidget(self.rateValueLabel, 2, 1, 1, 1)
        self.defaultTempLabel = QtWidgets.QLabel(self.homeTab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.defaultTempLabel.setFont(font)
        self.defaultTempLabel.setStyleSheet("qproperty-alignment:\'AlignCenter\'")
        self.defaultTempLabel.setObjectName("defaultTempLabel")
        self.gridLayout_3.addWidget(self.defaultTempLabel, 4, 0, 1, 1)
        self.modeLabel = QtWidgets.QLabel(self.homeTab)
        self.modeLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeLabel.sizePolicy().hasHeightForWidth())
        self.modeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.modeLabel.setFont(font)
        self.modeLabel.setStyleSheet("qproperty-alignment:\'AlignCenter\'")
        self.modeLabel.setObjectName("modeLabel")
        self.gridLayout_3.addWidget(self.modeLabel, 0, 0, 1, 1)
        self.serviceNoValueLabel = QtWidgets.QLabel(self.homeTab)
        self.serviceNoValueLabel.setText("")
        self.serviceNoValueLabel.setObjectName("serviceNoValueLabel")
        self.gridLayout_3.addWidget(self.serviceNoValueLabel, 3, 1, 1, 1)
        self.modeValuelabel = QtWidgets.QLabel(self.homeTab)
        self.modeValuelabel.setText("")
        self.modeValuelabel.setObjectName("modeValuelabel")
        self.gridLayout_3.addWidget(self.modeValuelabel, 0, 1, 1, 1)
        self.serviceNoLabel = QtWidgets.QLabel(self.homeTab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.serviceNoLabel.setFont(font)
        self.serviceNoLabel.setStyleSheet("qproperty-alignment:\'AlignCenter\'")
        self.serviceNoLabel.setObjectName("serviceNoLabel")
        self.gridLayout_3.addWidget(self.serviceNoLabel, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.homeTab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("qproperty-alignment:\'AlignCenter\'")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.homeTab)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 15, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.detailtableWidget = QtWidgets.QTableWidget(self.homeTab)
        self.detailtableWidget.setObjectName("detailtableWidget")
        self.detailtableWidget.setColumnCount(9)
        self.detailtableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailtableWidget.setHorizontalHeaderItem(8, item)
        self.gridLayout_2.addWidget(self.detailtableWidget, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.homeTab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.homeTab, icon, "")
        self.countTab = QtWidgets.QWidget()
        self.countTab.setObjectName("countTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.countTab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 3, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.countTab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_8.addWidget(self.pushButton, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.comboBox_6 = QtWidgets.QComboBox(self.countTab)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_2.addWidget(self.comboBox_6)
        self.label_13 = QtWidgets.QLabel(self.countTab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.comboBox_5 = QtWidgets.QComboBox(self.countTab)
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_2.addWidget(self.comboBox_5)
        self.label_18 = QtWidgets.QLabel(self.countTab)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.comboBox_4 = QtWidgets.QComboBox(self.countTab)
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_2.addWidget(self.comboBox_4)
        self.label_19 = QtWidgets.QLabel(self.countTab)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 2, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Count.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.countTab, icon1, "")
        self.settingTab = QtWidgets.QWidget()
        self.settingTab.setObjectName("settingTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.settingTab)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.setPushButton = QtWidgets.QPushButton(self.settingTab)
        self.setPushButton.setObjectName("setPushButton")
        self.horizontalLayout.addWidget(self.setPushButton)
        self.clearPushButton = QtWidgets.QPushButton(self.settingTab)
        self.clearPushButton.setObjectName("clearPushButton")
        self.horizontalLayout.addWidget(self.clearPushButton)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.gridLayout_7.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.settingTab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setStyleSheet("qproperty-alignment:\'AlignCenter\'")
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 6, 0, 1, 1)
        self.defaultFanComboBox = QtWidgets.QComboBox(self.settingTab)
        self.defaultFanComboBox.setObjectName("defaultFanComboBox")
        self.gridLayout_4.addWidget(self.defaultFanComboBox, 5, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 6, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 4, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setStyleSheet("qproperty-alignment:\'AlignCenter\'")
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 7, 0, 1, 1)
        self.coldRadioButton = QtWidgets.QRadioButton(self.settingTab)
        self.coldRadioButton.setObjectName("coldRadioButton")
        self.gridLayout_4.addWidget(self.coldRadioButton, 0, 1, 1, 1)
        self.lowTempLineEdit = QtWidgets.QLineEdit(self.settingTab)
        self.lowTempLineEdit.setObjectName("lowTempLineEdit")
        self.gridLayout_4.addWidget(self.lowTempLineEdit, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setStyleSheet("qproperty-alignment:\'AlignCenter\'")
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 4, 0, 1, 1)
        self.highTempLineEdit = QtWidgets.QLineEdit(self.settingTab)
        self.highTempLineEdit.setObjectName("highTempLineEdit")
        self.gridLayout_4.addWidget(self.highTempLineEdit, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.settingTab)
        self.label_3.setStyleSheet("qproperty-alignment:\'AlignCenter\'")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 5, 0, 1, 1)
        self.RangeComboBox = QtWidgets.QComboBox(self.settingTab)
        self.RangeComboBox.setObjectName("RangeComboBox")
        self.gridLayout_4.addWidget(self.RangeComboBox, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setStyleSheet("qproperty-alignment:\'AlignCenter\'")
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setStyleSheet("qproperty-alignment:\'AlignCenter\'")
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.defaultTempLineEdit = QtWidgets.QLineEdit(self.settingTab)
        self.defaultTempLineEdit.setObjectName("defaultTempLineEdit")
        self.gridLayout_4.addWidget(self.defaultTempLineEdit, 4, 1, 1, 1)
        self.hotRadioButton = QtWidgets.QRadioButton(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotRadioButton.sizePolicy().hasHeightForWidth())
        self.hotRadioButton.setSizePolicy(sizePolicy)
        self.hotRadioButton.setObjectName("hotRadioButton")
        self.gridLayout_4.addWidget(self.hotRadioButton, 0, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.settingTab)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 3, 0, 1, 1)
        self.serviceNoComboBox = QtWidgets.QComboBox(self.settingTab)
        self.serviceNoComboBox.setObjectName("serviceNoComboBox")
        self.gridLayout_4.addWidget(self.serviceNoComboBox, 7, 1, 1, 1)
        self.rateLineEdit = QtWidgets.QLineEdit(self.settingTab)
        self.rateLineEdit.setObjectName("rateLineEdit")
        self.gridLayout_4.addWidget(self.rateLineEdit, 6, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.line_2 = QtWidgets.QFrame(self.settingTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox_7 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_5.addWidget(self.checkBox_7, 7, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 5, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 8, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 7, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_5.addWidget(self.checkBox, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_5.addWidget(self.checkBox_2, 2, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_5.addWidget(self.checkBox_3, 3, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 6, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_5.addWidget(self.checkBox_5, 5, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_5.addWidget(self.checkBox_4, 4, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_5.addWidget(self.checkBox_6, 6, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_5.addWidget(self.checkBox_8, 8, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.settingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 0, 0, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_5.addWidget(self.checkBox_9, 1, 2, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_5.addWidget(self.checkBox_10, 2, 2, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_5.addWidget(self.checkBox_11, 3, 2, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_5.addWidget(self.checkBox_12, 4, 2, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_5.addWidget(self.checkBox_13, 5, 2, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_5.addWidget(self.checkBox_14, 6, 2, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_5.addWidget(self.checkBox_15, 7, 2, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.settingTab)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_5.addWidget(self.checkBox_16, 8, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_5)
        self.gridLayout_7.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 1, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.settingTab, icon2, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1270, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rangeLabel.setText(_translate("MainWindow", "温度范围"))
        self.rateLabel.setText(_translate("MainWindow", "费率"))
        self.defaultTempLabel.setText(_translate("MainWindow", "默认温度"))
        self.modeLabel.setText(_translate("MainWindow", "工作模式"))
        self.serviceNoLabel.setText(_translate("MainWindow", "服务对象数"))
        self.label.setText(_translate("MainWindow", "默认风速"))
        item = self.detailtableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "房间号"))
        item = self.detailtableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "类型"))
        item = self.detailtableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "状态"))
        item = self.detailtableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "目标温度"))
        item = self.detailtableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "当前温度"))
        item = self.detailtableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "目标风速"))
        item = self.detailtableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "当前风速"))
        item = self.detailtableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "能耗"))
        item = self.detailtableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "费用"))
        self.pushButton.setText(_translate("MainWindow", "生成统计报表"))
        self.label_13.setText(_translate("MainWindow", "年"))
        self.label_18.setText(_translate("MainWindow", "月"))
        self.label_19.setText(_translate("MainWindow", "日"))
        self.setPushButton.setText(_translate("MainWindow", "确定"))
        self.clearPushButton.setText(_translate("MainWindow", "重置"))
        self.label_8.setText(_translate("MainWindow", "最低温度"))
        self.label_12.setText(_translate("MainWindow", "费率"))
        self.label_17.setText(_translate("MainWindow", "RMB/kwh"))
        self.label_16.setText(_translate("MainWindow", "°C"))
        self.label_15.setText(_translate("MainWindow", "°C"))
        self.label_14.setText(_translate("MainWindow", "服务对象数"))
        self.coldRadioButton.setText(_translate("MainWindow", "制冷"))
        self.label_11.setText(_translate("MainWindow", "缺省温度"))
        self.label_3.setText(_translate("MainWindow", "默认风速"))
        self.label_10.setText(_translate("MainWindow", "温控范围"))
        self.label_9.setText(_translate("MainWindow", "温控模式"))
        self.hotRadioButton.setText(_translate("MainWindow", "制热"))
        self.label_28.setText(_translate("MainWindow", "最高温度"))
        self.checkBox_7.setText(_translate("MainWindow", "普通"))
        self.label_22.setText(_translate("MainWindow", "312A"))
        self.label_24.setText(_translate("MainWindow", "313A"))
        self.label_27.setText(_translate("MainWindow", "315A"))
        self.label_26.setText(_translate("MainWindow", "314A"))
        self.checkBox.setText(_translate("MainWindow", "普通"))
        self.label_21.setText(_translate("MainWindow", "311B"))
        self.label_20.setText(_translate("MainWindow", "311A"))
        self.checkBox_2.setText(_translate("MainWindow", "普通"))
        self.checkBox_3.setText(_translate("MainWindow", "普通"))
        self.label_23.setText(_translate("MainWindow", "312B"))
        self.label_25.setText(_translate("MainWindow", "313B"))
        self.checkBox_5.setText(_translate("MainWindow", "普通"))
        self.checkBox_4.setText(_translate("MainWindow", "普通"))
        self.checkBox_6.setText(_translate("MainWindow", "普通"))
        self.checkBox_8.setText(_translate("MainWindow", "普通"))
        self.label_29.setText(_translate("MainWindow", "房间号"))
        self.checkBox_9.setText(_translate("MainWindow", "VIP"))
        self.checkBox_10.setText(_translate("MainWindow", "VIP"))
        self.checkBox_11.setText(_translate("MainWindow", "VIP"))
        self.checkBox_12.setText(_translate("MainWindow", "VIP"))
        self.checkBox_13.setText(_translate("MainWindow", "VIP"))
        self.checkBox_14.setText(_translate("MainWindow", "VIP"))
        self.checkBox_15.setText(_translate("MainWindow", "VIP"))
        self.checkBox_16.setText(_translate("MainWindow", "VIP"))

import qt
